/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedPostsIndexRouteImport } from './routes/_protected/posts/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedDashboardTontinesRouteRouteImport } from './routes/_protected/dashboard/tontines/route'
import { Route as ProtectedDashboardCountriesRouteRouteImport } from './routes/_protected/dashboard/countries/route'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPostsIndexRoute = ProtectedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardTontinesRouteRoute =
  ProtectedDashboardTontinesRouteRouteImport.update({
    id: '/dashboard/tontines',
    path: '/dashboard/tontines',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDashboardCountriesRouteRoute =
  ProtectedDashboardCountriesRouteRouteImport.update({
    id: '/dashboard/countries',
    path: '/dashboard/countries',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/countries': typeof ProtectedDashboardCountriesRouteRoute
  '/dashboard/tontines': typeof ProtectedDashboardTontinesRouteRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/posts': typeof ProtectedPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/dashboard/countries': typeof ProtectedDashboardCountriesRouteRoute
  '/dashboard/tontines': typeof ProtectedDashboardTontinesRouteRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/posts': typeof ProtectedPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_protected/dashboard/countries': typeof ProtectedDashboardCountriesRouteRoute
  '/_protected/dashboard/tontines': typeof ProtectedDashboardTontinesRouteRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/posts/': typeof ProtectedPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/dashboard/countries'
    | '/dashboard/tontines'
    | '/dashboard'
    | '/posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/demo/tanstack-query'
    | '/dashboard/countries'
    | '/dashboard/tontines'
    | '/dashboard'
    | '/posts'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/demo/tanstack-query'
    | '/_protected/dashboard/countries'
    | '/_protected/dashboard/tontines'
    | '/_protected/dashboard/'
    | '/_protected/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/posts/': {
      id: '/_protected/posts/'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof ProtectedPostsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/tontines': {
      id: '/_protected/dashboard/tontines'
      path: '/dashboard/tontines'
      fullPath: '/dashboard/tontines'
      preLoaderRoute: typeof ProtectedDashboardTontinesRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/countries': {
      id: '/_protected/dashboard/countries'
      path: '/dashboard/countries'
      fullPath: '/dashboard/countries'
      preLoaderRoute: typeof ProtectedDashboardCountriesRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardCountriesRouteRoute: typeof ProtectedDashboardCountriesRouteRoute
  ProtectedDashboardTontinesRouteRoute: typeof ProtectedDashboardTontinesRouteRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedPostsIndexRoute: typeof ProtectedPostsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardCountriesRouteRoute: ProtectedDashboardCountriesRouteRoute,
  ProtectedDashboardTontinesRouteRoute: ProtectedDashboardTontinesRouteRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedPostsIndexRoute: ProtectedPostsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
